# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 18:56
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_imagesdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insta_id', models.CharField(blank=True, max_length=256, null=True)),
                ('insta_name', models.CharField(blank=True, max_length=256, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('lattitude', models.FloatField(blank=True, null=True)),
                ('yelp_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('opentable_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
    ]
