# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='lattitude',
            new_name='latitude',
        ),
    ]
